project:
  type: website
  title: "intoTheTidyverse"
  output-dir: docs

website:
  sidebar: 
    style: "docked"
    search: true
    contents:
      - text: "Into the tidyverse"
        href: index.qmd
      - text: "Welcome to the tidyverse"  
        href: intoTheTidyverse.qmd
      - text: "Episode 1 - Functions"
        href: episode_1_functions.qmd  
      - text: "Episode 2 - Data Transformations"
        href: episode_2_dataTransformations.qmd
  

format:
  html:
    page-layout: full
    theme: 
        light: flatly
        dark: darkly
#    css: styles.css
    toc: true
