---
title: "Episode 1 - Into the tidyverse"
engine: knitr
format: live-html
webr:
    packages:
---

Maybe this is your first encounter with R, or maybe you've self-taught and stumbled your way through a plot, or maybe you've been using base R for ages and you figure it's about time to check out this new 'tidyverse' (that's me, by the way). Whatever your situation, this workshop is going to introduce you to the tidyverse, get you started with some exercises, and then set you loose with enough tools to explore things comfortably (and safely) on your own.

## What is the tidyverse?

The tidyverse is a collection of R tools, which we call packages, that were designed to be easy to use, easy to read, and work well together. To understand the tidyverse, we need to know some of the history of R.

### The R programming language

R was created in 1993 by Ross Ihaka and Robert Gentleman at the University of Auckland. It was designed as a tool to teach statistics, and it's been widely adopted by the field of biology. Over time many people have developed R packages - packages can be approximately thought as like apps on a phone - which focus on specific analyses. For example, if you want to identify differentially expressed genes using RNA-seq data, there is an R package that can perform various statistical tests and normalisation steps. Actually, there are *lots* of packages that will do this, and the hard part is choosing which one to use. All of these packages are developed by the community, which is great, and initially they were all written in what we call "base R".

Base R, and all the R packages that were developed using it, are a bit like the English language: for those who grew up with it, it's beautifully flexible, expressive, and intuitive. For anyone learning it as an adult...why on earth is there a "g" in night? (Or a "k" in knight, for that matter). Base R packages, like the english language, are a mix of styles and formats depending on who wrote them.

### The tidyverse

The tidyverse is a series of packages that have been designed from the ground up to work together, using a consistent, logical style. It's written to be human readable, intuitive, and easy to learn. The tidyverse is highly popular and is well documented. My personal opinion: if I was going to learn R now, I would choose to focus on learning the tidyverse.

The tidyverse is also a mindset about how data should be presented and stored. Data is "tidy" if:

-   Each variable is stored in a column (variables could be Age, Height, Occupation).

-   Each observation is stored in a row (here, observations could be individuals).

Together, these rows and columns form a table.

## Into the tidyverse

In this workshop we will start out assuming you know nothing about R. We *will* assume that you are either doing this workshop using the live website, or have R and RStudio installed on your computer, or that you are using RStudio in a training environment\*. If you are using the live website or training environment, you will **not** need to install packages, but if you are working on your own device you will need to. Installing packages might sound intimidating, but it will only require copy-pasting a line of code.

We will first introduce the two building blocks of R: functions and objects. Simultaneously we will look at directory structure and your RStudio environment.

Once you know what a function is we will look at how functions work in the tidyverse style - this is where we will introduce you to the "pipe". The pipe, or "piping" is a way to pass information from one function to another.

This workshop places a strong focus on practice and repetition through exercises. You are attempting to learn a language, and you can't do that without practice. Once you have experience with the basics, we will increase the pace and introduce you to a wider toolbox of functions that can be used to achieve your goals.

\*If you need help with installing R and RStudio, we will have a supplementary page available to assist you.